---
title: "2018-11-1"
author: "林茂廷"
date: "11/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(showtext)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
library(ggplot2)
library(dplyr)
```

```{r}
library(lubridate)
library(dplyr)
library(tidyr)
library(readr)
# 引入資料
exData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6563&md5_url=9f65bdb6752389dc713acc27e93c1c38")

# 處理時間
exData$期間 %>% paste0("-01") %>% ymd() -> exData$期間

# 處理資料結構
exData %>% select(期間, "歐元USD/EUR","韓元KRW/USD","人民幣CNY/USD", "日圓JPY/USD", "新台幣NTD/USD") -> exData2

exData2 %>% gather(幣別, 匯率, -期間) -> exData2

# 處理變數class
exData2$幣別 %>% as.factor() -> exData2$幣別
exData2$匯率 %>% as.numeric() -> exData2$匯率

# 處理歐元
exData2$匯率[exData2$幣別=="歐元USD/EUR"]<-1/exData2$匯率[exData2$幣別=="歐元USD/EUR"]

# 以2017年1月為基期
exData2 %>% group_by(幣別) %>%
  mutate(匯率=匯率/匯率[期間==ymd("2017-01-01")]*100) %>% 
  ungroup() ->
  exData3

levels(exData3$幣別)[4]<-"歐元EUR/USD"
```

